import{a as p,S as f,i as n}from"./assets/vendor-64b55ca9.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&a(l)}).observe(document,{childList:!0,subtree:!0});function o(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(t){if(t.ep)return;t.ep=!0;const r=o(t);fetch(t.href,r)}})();async function d(i,e){const o="42307458-71f98d2a331f0bd294b8fc1ec",r="https://pixabay.com"+"/api/",l={key:o,q:i,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:e};return(await p.get(r,{params:l})).data}let c;const s={form:document.querySelector(".form"),input:document.querySelector(".input-search"),button:document.querySelector(".button"),gallery:document.querySelector(".gallery"),loader:document.querySelector(".loader"),buttonLoader:document.querySelector(".btn-more")};function m(i){return i.map(e=>`
      <li class="gal-item"><a href="${e.largeImageURL}">
            <img class="gal-image" src="${e.webformatURL}" alt="${e.tags}"></a>
            <div class="par-sect">
            <p> <span class="par-information">Likes</span> <br/> ${e.likes}</p>
            <p><span class="par-information">Views</span> <br/> ${e.views}</p>
            <p><span class="par-information">Comments</span> <br/> ${e.comments}</p>
            <p><span class="par-information">Downloads</span> <br/> ${e.downloads}</p>
            </div>
            </li>
      `).join("")}function h(i){const e=m(i);s.gallery.insertAdjacentHTML("beforeend",e),typeof c<"u"?c.refresh():c=new f(".gallery a",{captionsData:"alt",captionDelay:250})}class g{constructor(){this.userInput="",this.page=1,this.maxPage=void 0}async onFormSubmit(e){if(e.preventDefault(),this.clearGallery(),this.page=1,this.userInput=s.input.value.trim(),this.userInput===""){n.error({message:"Please enter a search query.",position:"topRight",transitionIn:"fadeInLeft"});return}s.gallery.innerHTML="",this.showLoader(),this.hideLoadBtn();try{const o=await d(this.userInput,this.page);this.maxPage=Math.ceil(o.totalHits/15),o.hits.length===0?(this.hideLoader(),n.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",transitionIn:"fadeInLeft"})):h(o.hits)}catch(o){n.error({message:o.message||"An error occurred. Please try again later.",position:"topRight",transitionIn:"fadeInLeft"})}this.hideLoader(),this.checkBtnVisibleStatus(),e.target.reset()}async onLoadMoreClick(){this.page+=1,this.showLoader();try{const e=await d(this.userInput,this.page);if(this.hideLoader(),e.hits.length>0){h(e.hits);const o=s.gallery.firstElementChild;if(o){const a=o.getBoundingClientRect().height;scrollBy({behavior:"smooth",top:a*2})}}else n.show({message:"We're sorry, but you've reached the end of search results.",position:"topRight",color:"blue",iconUrl:imgIcon,transitionIn:"fadeInLeft"})}catch(e){n.error({message:e.message||"An error occurred. Please try again later.",position:"topRight",transitionIn:"fadeInLeft"})}this.checkBtnVisibleStatus()}showLoadBtn(){s.buttonLoader.classList.remove("hidden")}hideLoadBtn(){s.buttonLoader.classList.add("hidden")}showLoader(){s.loader.style.display="block"}hideLoader(){s.loader.style.display="none"}clearGallery(){s.gallery.innerHTML=""}checkBtnVisibleStatus(){this.page>=this.maxPage?(this.hideLoadBtn(),this.hideLoader(),n.show({message:"We're sorry, but you've reached the end of search results.",position:"topRight",color:"blue",iconUrl:imgIcon,transitionIn:"fadeInLeft"})):this.showLoadBtn()}}const u=new g;s.form.addEventListener("submit",i=>u.onFormSubmit(i));s.buttonLoader.addEventListener("click",()=>u.onLoadMoreClick());
//# sourceMappingURL=commonHelpers.js.map
